[tool.poetry]
name = "pysut"
version = "0.1.0"
description = "A simple unit test library"
authors = ["dhzdhd"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.7.0"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.2"

[tool.taskipy.tasks]
example = "python examples/__main__.py"
test = "python -m unittest tests"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
