[[cases]]
[test_case_1]
inputs = [1, 2]
outputs = 3
metadata = "Basic addition functionality"

[test_case_2]
inputs = [10, 0]
outputs = "Division by zero error"
metadata = "Division with zero"

[test_case_3]
input = ""
output = ""
metadata = "Custom comparison logic"
