[[cases]]
name = "test case 1"
init = [1, 2]
inputs = [[1, 8, 6, 2, 5, 4, 8, 3, 7], 2]
outputs = 49
metadata = "Basic addition functionality"

[[cases]]
name = "test case 2"
init = [1, 2]
i = [[1, 2, 1], 2]
o = 5
metadata = "Division with zero"

[[cases]]
name = "test case 3"
init = [1, 7]
input = [[1, 2, 3, 1], 2]
output = 3
metadata = "Custom comparison logic"
