i = [
    [
        [
            1,
            8,
            6,
            2,
            5,
            4,
            8,
            3,
            7,
        ],
        2,
    ],
    [
        [
            1,
            2,
            1,
        ],
        2,
    ],
    [
        [
            1,
            2,
            1,
        ],
        2,
    ],
    [
        [
            1,
            2,
            1,
        ],
        2,
    ],
    [
        [
            1,
            2,
            1,
        ],
        2,
    ],
    [
        [
            1,
            2,
            1,
        ],
        2,
    ],
    [
        [
            1,
            2,
            1,
        ],
        2,
    ],
]
out = [49, 5, 3, 3, 3, 2, 2]
init = [1, "hi"]
