name: Build and publish package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build package
        run: poetry build

      - name: Generate release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: pysvt
          body_path: CHANGELOG.md
          repository: dhzdhd/pysvt
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*

      - name: Setup API token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Publish package to PyPI
        run: poetry publish
